name: Lint
# Lint runs golangci-lint over the entire Juno repository.
# This workflow is run on every pull request and push to master.
# The `golangci` will pass without running if no *.{go, mod, sum} files have been changed.
on:
  pull_request:
  push:
    branches:
      - cosmos/*

jobs:
  GolangCI:
    name: golangci-lint
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Compute diff 📜
        uses: technote-space/get-diff-action@v6.1.0
        with:
          SUFFIX_FILTER: |
            .go
            .mod
            .sum

      - name: Setup Go 🧰
        if: "env.GIT_DIFF != ''"
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Run lint ✅
        if: "env.GIT_DIFF != ''"
        run: make lint
